### ISSUE TITLE
Compatibility for Next.Js 15

### ISSUE THREAD

**Issue by mrdexign** [TheSGJ/nextjs-toploader#105]
Hello,
I've successfully implemented top-loader in several of my Next.js 14 projects with great results. 
However, I've noticed that it's no longer functioning in my latest project using Next.js 15.

![image](https://github.com/user-attachments/assets/a61c7e7a-3728-4f44-9a3d-6f685ad4637c)

**I would greatly appreciate if you could add compatibility support for the latest Next.js version.**

Thanks.

**Comment by thatkev** [comment]
It works with `"next": "^15.1.0"` for me

**Comment by mrdexign** [comment]
@thatkev 
I greatly appreciate your solution,
It's working fine right now.

By the way, I discovered that while Next.js 15.0 had an issue where the routeChangeStart callback wasn't firing, this has been fixed in version 15.1.

![image](https://github.com/user-attachments/assets/a65f5db2-96c6-4171-807b-d6ee9977f227)
