### ISSUE TITLE
Configuration not working for showSpinner

### ISSUE THREAD

**Issue by Sisableng** [TheSGJ/nextjs-toploader#11]
i set showSpinner to false and its not change anything, i mean the spinner still showing
i import this toploader in root layout.tsx, i use latest version of nextjs  for now the version is "13.4.2"

here is my configuration
`<NextTopLoader color="#F43F5E" showSpinner={false} />`

**Comment by TheSGJ** [comment]
Can you provide more details/code , or the reproduce of this bug using codesandbox. Sometimes hot reload may not work, so you might have to reload once for changes to occur.

**Comment by Sisableng** [comment]
i set `showSpinner` to `false` then i reload the page, but the spinner still showing at the top right of page

**Comment by Sisableng** [comment]
now is fixed, thanks dev

**Comment by Sisableng** [comment]
now is fixed, thanks dev

**Comment by ssk090** [comment]
> now is fixed, thanks dev

How did you fix ?
