### ISSUE TITLE
Hydration error after installing toploader

### ISSUE THREAD

**Issue by tonyxiao** [TheSGJ/nextjs-toploader#12]
<img width="1010" alt="image" src="https://github.com/TheSGJ/nextjs-toploader/assets/696842/e63bfa0a-2b76-4c93-8be3-065980e80624">
After installing top loader I'm getting this warning from next.js

**Comment by tonyxiao** [comment]
New info, this doesn't happen in `use client` components and only in server components

**Comment by laurent512** [comment]
issue still present for me

**Comment by TheSGJ** [comment]
This error only happens when you use TopLoader outside `<body></body>` tags. To solve this error you must use TopLoader inside the `<body></body>` tags.
