### ISSUE TITLE
Hydration error (app directory)

### ISSUE THREAD

**Issue by ishaan1013** [TheSGJ/nextjs-toploader#20]
Adding the component into the root layout gives a hydration error.

`app/layout.js`:
```tsx
import NextTopLoader from 'nextjs-toploader';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
```
![image](https://github.com/TheSGJ/nextjs-toploader/assets/69771365/b9188332-2a7e-4031-9e78-0b1356b4188e)

Putting `<NextTopLoader />` into a client component and using that in the root layout gives the same error.

**Comment by uwussimo** [comment]
### The same issue here, let me know if you find any fix.

**Comment by uwussimo** [comment]
I figured out the issue, so providers should be inside the body component...
