### ISSUE TITLE
Allow to Control the zIndex via prop

### ISSUE THREAD

**Issue by amandeeptherockstar** [TheSGJ/nextjs-toploader#26]
As per the code of library default zIndex for loader and progress bar is 1031, While using this library with Material UI whose app bar is having the `zIndex-1100`, The loader and progress bar goes behind the App bar.

Adding a reference to this link -https://mui.com/material-ui/customization/z-index/

**Comment by karlhorky** [comment]
Should this be closed, now that #27 was merged and [`nextjs-toploader@1.5.3`](https://github.com/TheSGJ/nextjs-toploader/releases/tag/v1.5.3) was published?
