### ISSUE TITLE
newUrl is undefined in some cases

### ISSUE THREAD

**Issue by DiiiaZoTe** [TheSGJ/nextjs-toploader#3]
Hey,
I was playing around again with this after the issue with the anchor.
This allowed me to find another issue.

After you configure NProgress inside your `navLink.addEventListener('click', ....`

```
let currentUrl = window.location.href;
let newUrl = event.target.href;
```

If you refresh the page, and click on a link, the `newUrl` comes back as `undefined`. I have no idea why is that though.

Add `console.log(currentUrl, newUrl)` after you assign them to see it.

I was able to find this because the new function I added for anchors does `new URL(newUrl)` which fails because `newUrl` is `undefined`

**Comment by TheSGJ** [comment]
Is this happening for the version 1.2.1?, I just published the fixes with version 1.2.1 for the package on npm.

**Comment by DiiiaZoTe** [comment]
This issue was present on any version I'm pretty sure

**Comment by TheSGJ** [comment]
Btw, I have now refactored the code for `NextTopLoader` in `useEffect` hook, and I have tested it out. And I have fixed the `event.target.href` to `event.currentTarget.href` in Js And in Typescript: `(event.currentTarget as HTMLAnchorElement).href;`. This seemed to fix the bug for Fix the `newUrl` returning as undefined value for few anchor tags (You can see changes in CHANGELOG.md)

**Comment by DiiiaZoTe** [comment]
You may also refactor the code to simplify the NProgress.configure
You can utilize the ?? nullish coalescing operatorcoalescing

Something like:
```js
NProgress.configure({ 
  showSpinner: props.showSpinner ?? here_put_default_value,
  speed: props.speed ?? here_put_default_value,
  etc...
});
```

**Comment by TheSGJ** [comment]
> You may also refactor the code to simplify the NProgress.configure You can utilize the ?? nullish coalescing operatorcoalescing
> 
> Something like:
> 
> ```js
> NProgress.configure({ 
>   showSpinner: props.showSpinner ?? here_put_default_value,
>   speed: props.speed ?? here_put_default_value,
>   etc...
> });
> ```



> You may also refactor the code to simplify the NProgress.configure You can utilize the ?? nullish coalescing operatorcoalescing
> 
> Something like:
> 
> ```js
> NProgress.configure({ 
>   showSpinner: props.showSpinner ?? here_put_default_value,
>   speed: props.speed ?? here_put_default_value,
>   etc...
> });
> ```

Thanks, Got it.
