### ISSUE TITLE
Component work on first load but not after

### ISSUE THREAD

**Issue by harkor** [TheSGJ/nextjs-toploader#4]
Hello,

I just discovered your solution.

Thanks for your work.

When I load my app and click on my navigation, toploader work like a charm, if I change page the loader work but after that when I change to another page, toploader never be displayed.

[Reproduction of the issue](https://codesandbox.io/p/sandbox/heuristic-rain-f0pzbk)

Thanks

**Comment by gwendall** [comment]
Thanks for sharing. I can see of two ways to easily enable it for client-side rendered (you probably thought of them too but worth sharing!):
- use a `MutationObserver` in the `useEffect` hook to catch click events on dynamically inserted links
- use a global click event handler and detect in it if the clicked element is a link to trigger the progress indicator

Is it a direction you are considering?

**Comment by gwendall** [comment]
Made a PR for option 2: https://github.com/TheSGJ/nextjs-toploader/pull/7

**Comment by TheSGJ** [comment]
I've merged the PR (#7), it added the client side detection for the navigation. With the version 1.3.2 of `nextjs-toploader` should work for client side rendered links.
