### ISSUE TITLE
Gets stuck if href="#"

### ISSUE THREAD

**Issue by nabtron** [TheSGJ/nextjs-toploader#42]
It should ignore if the href="#", instead gets stuck

**Comment by nabtron** [comment]
can be solved by adding code after line 148.

Add after:
`          const newUrl = (anchor as HTMLAnchorElement).href;`

making it:
```
          const newUrl = (anchor as HTMLAnchorElement).href;
          if((newUrl.charAt(newUrl.length - 1)) == "#") return false;

```

**Comment by TheSGJ** [comment]
Duplicate of #8
