### ISSUE TITLE
TopLoader stopped showing after upgrade to Next v14.

### ISSUE THREAD

**Issue by ekimcem** [TheSGJ/nextjs-toploader#45]
I have updated my proejct ot Next 14 and I can not able to see toploader.

In app/layout.tsx

```
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <NextTopLoader height={500} zIndex={9999} color="black" />
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
```

I have tried to make layout.tsx to a client component, it still not working.

**Comment by r0ld3x** [comment]
Working on mine. :)

**Comment by TheSGJ** [comment]
> I have updated my proejct ot Next 14 and I can not able to see toploader.
> 
> In app/layout.tsx
> 
> ```
> import { Toaster } from "@/components/ui/toaster";
> import "@/styles/globals.css";
> import type { Metadata } from "next";
> import NextTopLoader from "nextjs-toploader";
> 
> 
> 
> export default function RootLayout({ children }: { children: React.ReactNode }) {
>   return (
>     <html lang="en" suppressHydrationWarning>
>       <NextTopLoader height={500} zIndex={9999} color="black" />
>       <body>
>         {children}
>         <Toaster />
>       </body>
>     </html>
>   );
> }
> ```
> 
> I have tried to make layout.tsx to a client component, it still not working.

Seems like you're not using the TopLoader inside the body tags, just include the TopLoader inside the body tags.

```
export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
     <html lang="en">
       <body>
         <NextTopLoader height={500} zIndex={9999} color="black" />
         {children}
         <Toaster />
       </body>
     </html>
   );
 }
```
