### ISSUE TITLE
e.preventDefault() does not prevent animation

### ISSUE THREAD

**Issue by imclint21** [TheSGJ/nextjs-toploader#50]
Hi,

In a nested button inside a `Link`, if you call `preventDefault`, it does not prevent the animation.

```tsx
<Link href={"/somewhere"}>
    <button onClick={(e) => e.preventDefault()}>Hey</button>
</Link>
```

Regards

**Comment by lucasoz** [comment]
There is happening in my code

**Comment by tomcru** [comment]
This kinda makes sense, as the Toploader doesn't know what you are intending to do. For example, you could prevent the default -> but then still navigate to another page.

But I'm wondering if it's safe to assume that if `preventDefault()` was called - you are not looking to navigate to another page, and therefore don't want a Toploader.

**Comment by imclint21** [comment]
I confirm that it works nice using both like this:

```jsx
event.preventDefault();
event.nativeEvent.stopImmediatePropagation();
```
