### ISSUE TITLE
issue nextjs version 14.0.3 not finish loader

### ISSUE THREAD

**Issue by monir6163** [TheSGJ/nextjs-toploader#58]
see screenshot: https://prnt.sc/7PcLZPeovabN

**Comment by Jings** [comment]
Please see discussion in Issue #56 
It is known and caused by a behaviour change in the current NextJS 14.0.3 Release.

**Comment by netstermonir** [comment]
yes, I see but why we are using the next js old version? You fix and update your package. thanks

**Comment by favfly-dev** [comment]
Please fix this issue **ASAP**, I am facing problem with Next js Top loader after Next JS v14.0.3 upgrade. You need to fix this ASAP , otherwise, it would be breaking the production level website/applications

**Comment by Super-Kenil** [comment]
@monir6163 This is an  DUPLICATE issue, refer to the first issue here #56 . Mark this as closed

The #56 issue is fixed in the new Nextjs v14.0.4
