### ISSUE TITLE
Animation continues indefinitely when replacing the current route

### ISSUE THREAD

**Issue by harsh253** [TheSGJ/nextjs-toploader#66]
Nextjs - **13.4.6**
nextjs-toploader - **1.6.4**

**Current behaviour** - 
When using with nextjs' Link component , it works fine in a regular navigation but when I provide "replace" prop to Link component to replace the current route with a new route, the progress bar animation continues indefinitely even after the route has been replaced and the page is completely rendered.

**Expected behaviour** - 
The progress bar should complete the animation on successful navigation and stop the animation

**Comment by Steveb599** [comment]
dooesn't work fine for me with Link component as well, next version 14.0.3

**Comment by mjcarnaje** [comment]
doesn't work fine for me as well with <Link replace />

next - 14.0.0
nextjs-toploader - 1.6.6

**Comment by mbeaudru** [comment]
Moving to https://github.com/tomcru/holy-loader in the meantime (referred in this issue) since it fixes the replace problem under the hook 👍

**Comment by AndlerRL** [comment]
I this still an issue? I had the same issue with version `1.6.4` a couple of months ago.
